version: "3.9"
services:
  app:
    image: openjdk:19-jdk-alpine3.16
    container_name: app
    depends_on:
      - db
    volumes:
      - "./target/Todeb-Patika-Java-Spring-Bootcamp-Credit-Score-Application-Project-0.0.1-SNAPSHOT.jar:/Todeb-Patika-Java-Spring-Bootcamp-Credit-Score-Application-Project-0.0.1-SNAPSHOT.jar"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Todeb_Credit_Application
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8050:8050
    command: ["java", "-jar", "Todeb-Patika-Java-Spring-Bootcamp-Credit-Score-Application-Project-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:14.4-alpine3.16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: Todeb_Credit_Application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  # swagger:
  #   image: swaggerapi/swagger-ui
