-- DROP TABLE IF EXISTS customer, credit_application,application_result, customer_application_results CASCADE;
DROP TABLE IF EXISTS customer, credit_application CASCADE;

CREATE TABLE customer
(
    national_identity_number VARCHAR(11) PRIMARY KEY ,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    monthly_income NUMERIC(15,2) NOT NULL,
    gender    VARCHAR(10),
    age       INT,
    phone     VARCHAR(15) NOT NULL,
    email     VARCHAR(25) UNIQUE
);

CREATE TABLE credit_application
(
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_application_date DATE NOT NULL,
    credit_result VARCHAR NOT NULL,
    credit_limit NUMERIC(15,2) DEFAULT 0.00,
    application_status VARCHAR NOT NULL,
    national_identity_number VARCHAR(11) NOT NULL,
    FOREIGN KEY (national_identity_number) REFERENCES customer(national_identity_number)

);