DROP TABLE IF EXISTS customer, credit_application, approved_credit  CASCADE;

CREATE TABLE customer
(
    national_id VARCHAR(11) PRIMARY KEY ,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    credit_score VARCHAR,
    monthly_income NUMERIC(15,2) NOT NULL,
    gender    VARCHAR(10),
    age       INT,
    phone_no     VARCHAR(15) NOT NULL,
    e_mail     VARCHAR(25) UNIQUE
);

CREATE TABLE credit_application
(
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_date TIMESTAMP NOT NULL,
    credit_result VARCHAR NOT NULL,
    credit_limit NUMERIC(15,2) DEFAULT 0.00,
    application_status VARCHAR NOT NULL,
    customer_national_id VARCHAR(11) NOT NULL,
    FOREIGN KEY (customer_national_id) REFERENCES customer(national_id)

);

CREATE TABLE credit
(
    credit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_date TIMESTAMP,
    credit_limit NUMERIC(15,2) DEFAULT 0.00,
    credit_application_national_id VARCHAR(11) NOT NULL,
    FOREIGN KEY (credit_application_national_id) REFERENCES credit_application(application_id)
);
CREATE TABLE users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(25) UNIQUE,
    password VARCHAR(25),
    username VARCHAR(50) NOT NULL,

);
CREATE TABLE roles
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
);
CREATE TABLE user_roles
(
    users(id) INT,
    roles(id) INT,

);