DROP TABLE IF EXISTS customer, credit_application, approved_credit  CASCADE;

CREATE TABLE customer
(
    national_id VARCHAR(11) PRIMARY KEY ,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    monthly_income NUMERIC(15,2) NOT NULL,
    gender    VARCHAR(10),
    age       INT,
    phone_no     VARCHAR(15) NOT NULL,
    e_mail     VARCHAR(25) UNIQUE


);

CREATE TABLE credit_application
(
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_date DATE NOT NULL,
    credit_result VARCHAR NOT NULL,
    credit_limit NUMERIC(15,2) DEFAULT 0.00,
    application_status VARCHAR NOT NULL,
    national_id VARCHAR(11) NOT NULL,
    FOREIGN KEY (national_id) REFERENCES customer(national_id)

);

CREATE TABLE approved_credit
(
    credit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_date DATE NOT NULL,
    credit_limit NUMERIC(15,2) DEFAULT 0.00,
    national_id VARCHAR(11) NOT NULL,
    FOREIGN KEY (national_id) REFERENCES customer(national_id)

);